### ISSUE TITLE
Does not build for me today - missing file?

### ISSUE THREAD

**Issue by quicklisp** [rpav/ScriptL#4]
I get this:

    The path #P"/home/quicklisp/quicklisp-controller/dist/build-cache/scriptl/c61fc9f8a468c8eb34fe943c6ef16ff09eccfce7/scriptl-20150903-git/bin/scriptl" does not exist.

Build log is here: http://report.quicklisp.org/2015-09-03/failure-report/scriptl.html#scriptl

**Comment by rpav** [comment]
Ah, looks like the `bin/` directory wasn't being kept around.  I've pushed 81f2016603a5881988aeda64e2f5d25a005568a8 which adds a dummy file which should hopefully fix this.  Thanks.

**Comment by quicklisp** [comment]
Works for me, thanks!
