### ISSUE TITLE
[Questions] Script and run directories

### ISSUE THREAD

**Issue by therockmandolinist** [rpav/ScriptL#6]
I was wondering:
- Is there a way to create scripts elsewhere/at a specified directory (from inside lisp) ? (Some option to make-script I missed or something like that?)

- Is there a way for scripts to have a notion of where they're being run? For a kinda dumb example, if I wrote:
  ```
  (defun my-ls ()
    (format t (with-output-to-string (out)
                (run-program "/bin/ls" '() :output out))))
  
  (scriptl:make-script "ls" 'my-ls)
  
  ```
  Any calls to the ls script would only list the files where the script itself resides, not for the directory where the script is being called from.

**Comment by rpav** [comment]
Actually they should not; when scripts get called in, `*default-pathname-defaults*` should be bound to the caller's cwd.  This should be enough for anything inside the lisp, using `merge-pathnames`, but you may want to pass it on to things like `run-program`, where it's unfortunate `*default-pathname-defaults*` isn't the default.

**Comment by therockmandolinist** [comment]
@rpav Ah, I see. when using
```
(defun my-ls ()
  (dolist (file (directory "*.*"))
    (write-line (namestring file))))
```
instead, it works as expected. Thanks! So there's no way around this with run-program?

Also, what about making scripts in a different directory than `*default-pathname-defaults*` ?

**Comment by therockmandolinist** [comment]
Great, all of this seems to work. Thanks!

**Comment by therockmandolinist** [comment]
Er, scratch that - I dont think locally binding `*default-pathname-defaults*` is quite doing the trick.

**Comment by rpav** [comment]
Try with bef41db, apparently it wasn't doing `merge-pathnames` on the actual target usage.
